# Site settings
title: Meishan Fan
email: web@meimei.lol
description: > # this means to ignore newlines until "baseurl:"
  Things I've done and made.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
# github_username:  

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

permalink: /:path/

collections:
  projects:
    output: true
    permalink: /projects/:path/
  backpacking: 
    output: true
    permalink: /backpacking/:path/
  curtis: 
    output: true
    permalink: /curtis/:path/
  contact: 
    output: true
    permalink: /contact/:path/


